// Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

[%hardbreaks]
. Install Nodejs 10.13.0 or later 
.. example: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html[Install Nodejs on an EC2 instance]
. Install AWS CDK CLI using Node Package Manager(npm)
+
[,bash]
----
npm install -g aws-cdk
----
+ 
For additional info see the https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html[AWS Cloud Development Kit Developer guide]
. Install zip package
+
[,bash]
----
sudo yum install zip    # RHEL/CentOS
sudo apt install zip    # Debian/Ubuntu
----
+
. Load your AWS credentials into your dev environment (may be done via AWSCLI)
. Obtain your Radiant Logic License
. Obtain you Immuta license 
+
NOTE: The Immuta passwords required in step 3 of the install instructions will be provided by Immuta once a license is purchased.

== Deployment steps
[%hardbreaks]
. Navigate to the Data Fabric Security root folder. 
+
[,bash]
----
   cd <path>/data-fabric
----
. Install all packages. 
+
[,bash]
----
   npm install
----
. Open the file \<path>/data-fabric/config/dev.yaml for editing and set the variables for your environment.
+ 
See [Deployment Configuration](#deployment-configuration) section for additional details.
. Run the DFS Preparation script 
+
[,bash]
----
   chmod +x dfs-staging.sh 
   ./dfs-staging.sh 
----
. Bootstrap CDK. 
+
[,bash]
----
cdk bootstrap aws://<ACCOUNT_ID>/<REGION>
----
. Deploy the solution 
+
[,bash]
----
   chmod +x dfs-solution-install.sh 
   ./dfs-solution-install.sh 
----
+ 
NOTE: It takes about 20 minutes to deploy the solution.
. Once deployment is complete, Copy the output from the deployment and save it for later use. An example of the output:
+
Example output for DataFabricStack
+
[,bash]
----
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityhostedzone8A7A666ERef412EFD8E = Z08846025FQL5G34G3RSN
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityvpc3D851B3DRef8F8BED20 = vpc-0k86a8r6550x470sd
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityvpcPrivateSubnet1SubnetD144D644RefCA2E36A0 = subnet-05c58c03655b07e96
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityvpcPrivateSubnet2SubnetC59876D4RefB9149745 = subnet-0355b2b6384b7a984
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityvpcPublicSubnet1Subnet364D7A24RefCE325DB3 = subnet-0b384f6b1a3cdee0d
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritycorestackNestedStackdatafabricsecuritycorestackNestedStackResource0E29B9E3OutputsDataFabricStackdatafabricsecuritycorestackdatafabricsecurityvpcPublicSubnet2SubnetE8E85537RefFE30536F = subnet-09eaf0abdec1vf6e2
DataFabricStack.ExportsOutputFnGetAttdatafabricsecuritykeyEF30DCE5Arn6660AD21 = arn:aws-us-gov:kms:us-gov-west-1:123456789012:key/a5n6bs39-8yfr-7tww-m544-57bk737tay0f
DataFabricStack.ExportsOutputRefdatafabricsecuritykubectl66B18AE6595A4A51 = arn:aws-us-gov:lambda:us-gov-west-1:123456789012:layer:datafabricsecuritykubectl44B16AB6:5
----
+
Example output for DataFabricStack/data-fabric-security-eks-cluster
+
[,bash]
----
DataFabricStackdatafabricsecurityeksclusterCA551CED.ClusterArn = arn:aws-us-gov:eks:us-gov-west-1:123456789012:cluster/data-fabric-security-eks-cluster
DataFabricStackdatafabricsecurityeksclusterCA551CED.EKSAdminRole = arn:aws-us-gov:iam::123456789012:role/DataFabricStackdatafabric-datafabricsecurityeksclu-16OBLBQDF1383
DataFabricStackdatafabricsecurityeksclusterCA551CED.datafabricsecurityadminplatformteamteamadmin = arn:aws-us-gov:iam::123456789012:role/Admin
DataFabricStackdatafabricsecurityeksclusterCA551CED.datafabricsecurityeksclusterClusterName6BCF1F10 = data-fabric-security-eks-cluster
DataFabricStackdatafabricsecurityeksclusterCA551CED.datafabricsecurityeksclusterConfigCommand978D3532 = aws eks update-kubeconfig --name data-fabric-security-eks-cluster --region us-gov-west-1 --role-arn arn:aws-us-gov:iam::123456789012:role/DataFabricStackdatafabric-datafabricsecurityeksclu-14T5IMKRMS7JT
DataFabricStackdatafabricsecurityeksclusterCA551CED.datafabricsecurityeksclusterGetTokenCommand1D6ABA05 = aws eks get-token --cluster-name data-fabric-security-eks-cluster --region us-gov-west-1 --role-arn arn:aws-us-gov:iam::123456789012:role/DataFabricStackdatafabric-datafabricsecurityeksclu-14T5IMKRMS7JT
----

. See the Operational Guide for additional configuration of Radiant Logic and 

=== Deployment Configuration

The following tables represent the parameters that are set in the config/dev.yaml file

==== Global

[%header,cols="2,6,1"]
|===
|Parameter |Description |Default 
|AWSAccountID |ID of the AWS Account to deploy solution |"" 
|AWSRegion |AWS region to deploy solution |""
|Domain |Domain name that will be used for the solution |"" 
|===

==== Networking

[%header,cols="2,6,1"]
|===
| Parameter 
| Description
| Default 

| VpcId     | ID of the VPC to use for the deployment (leave blank if you want to create a new VPC) | ""      
| SubnetA   | Private subnet in AZ1 (leave blank if you want to create a new subnet)                | ""      
| SubnetB   | Private subnet in AZ2 (leave blank if you want to create a new subnet)                | ""      
| MaxAZs    | Maximum availability zones                                                            | 2       
|===

==== EKS

[%header,cols="2,6,1"]
|===
| Parameter         
| Description
| Default    

| EKSAdminRole | Admin role ARN for EKS (This ARN must be an existing role in the account with AdminAccess permission) | ""         
| EKSEndpointAccess | EKS endpoint access type (Valid inputs are "PUBLIC", "PRIVATE", or "" for both) | ""         
| InstanceType      | Instance type for the EKS cluster                                               | "m5.large" 
| ClusterSize       | Size of the EKS cluster                                                         | 3          
|=== 

==== Immuta

[%header,cols="2,6,1"]
|===
| Parameter
| Description
| Default 

| Deploy                               | Boolean to deploy the component   | true    
| ChartVersion                         | Immuta Helm Chart version         | ""
| ImmutaVersion                        | Version of Immuta to Install      | ""
| ImageTag                             | Docker image tag                  | ""
| Instance.Username                    | Immuta instance username          | ""      
| Instance.Password                    | Immuta instance password          | ""      
| Database.ImmutaDBPassword            | Database password                 | ""      
| Database.ImmutaDBSuperUserPassword   | Database superuser password       | ""      
| Database.ImmutaDBReplicationPassword | Database replication password     | ""      
| Database.ImmutaDBPatroniApiPassword  | Database Patroni API password     | ""      
| Query.ImmutaQEPassword               | Query engine password             | ""      
| Query.ImmutaQESuperUserPassword      | Query engine superuser password   | ""      
| Query.ImmutaQEReplicationPassword    | Query engine replication password | ""      
| Query.ImmutaQEPatroniApiPassword     | Query engine Patroni API password | ""      
|===

==== Radiant Logic

[%header,cols="2,6,1"]
|===
| Parameter    | Description                                 | Default 
| Deploy       | Boolean to deploy the component             | true    
| ZkChartVersion | Zookeeper Chart Version                   | ""
| FidChartVersion | FID Chart Version                        | ""
| FidImageTagVersion | FID Cocker Image Tag                  | ""
| License      | License for Radiant Logic                   | ""      
| RootPassword | Password to be used for the root admin user | ""      
|===